# Generated by Django 5.2.8 on 2025-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('visitdate', models.DateTimeField()),
                ('medicalhistory', models.TextField()),
            ],
        ),
    ]
