# Generated by Django 5.2.8 on 2025-11-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_medicalrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medicalhistory',
            new_name='medical_history',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='visitdate',
            new_name='visit_date',
        ),
    ]
